name: Deploy meta-ai-api to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS \
          --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t meta-ai-api:${{ github.sha }} .

      - name: Tag image
        run: |
          docker tag meta-ai-api:${{ github.sha }} \
          ${{ secrets.ECR_REGISTRY }}/awinteck-services:meta-ai-api-${{ github.sha }}

      - name: Push image to ECR
        run: |
          docker push \
          ${{ secrets.ECR_REGISTRY }}/awinteck-services:meta-ai-api-${{ github.sha }}

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.ECR_REGISTRY }}/awinteck-services:meta-ai-api-${{ github.sha }}
            docker stop meta-ai-api || true
            docker rm meta-ai-api || true
            docker run -d -p 5000:5000 \
              --name meta-ai-api \
              --restart always \
              --env-file envs/.env.meta-ai-api \
              ${{ secrets.ECR_REGISTRY }}/awinteck-services:meta-ai-api-${{ github.sha }}